---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boinceinstein
  # namespace: boinc
  labels:
    app: boinceinstein
spec:
  replicas: 1
  template:
    metadata:
      name: boinceinstein
      # namespace: boinc
      labels:
        app: boinceinstein
    spec:
      containers:
        - name: boinceinstein
          image: boinc/client
          env:
          - name: EINSTEINACCESSKEY
            valueFrom:
              secretKeyRef:
                name: boinc-einstein-appkey
                key: einstein-appkey
          - name: TZ
            value: "Europe/Prague"
          - name: BOINC_GUI_RPC_PASSWORD
            value: "123"
          - name: BOINC_CMD_LINE_OPTIONS
            value: "--allow_remote_gui_rpc --attach_project http://einstein.phys.uwm.edu/ $EINSTEINACCESSKEY"
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 31416
            name: manager
            protocol: TCP
  selector:
    matchLabels:
      app: boinceinstein
---
apiVersion: v1
kind: Service
metadata:
  name: boinceinstein
  # namespace: boinc
  # annotations:
  #   metallb.universe.tf/address-pool: #Replace this comment with your MetalLB Pool Name
spec:
  selector:
    app: boinceinstein
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
    - port: 31416
      name: manager
      protocol: TCP
  type: LoadBalancer