---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boincseti
  # namespace: boinc
  labels:
    app: boincseti
spec:
  replicas: 1
  template:
    metadata:
      name: boincseti
      # namespace: boinc
      labels:
        app: boincseti
    spec:
      containers:
        - name: boincseti
          image: boinc/client
          env:
          - name: SETIACCESSKEY
            valueFrom:
              secretKeyRef:
                name: boinc-seti-appkey
                key: seti-appkey
          - name: TZ
            value: "Europe/Prague"
          - name: BOINC_GUI_RPC_PASSWORD
            value: "123"
          - name: BOINC_CMD_LINE_OPTIONS
            value: "--allow_remote_gui_rpc --attach_project https://setiathome.berkeley.edu $SETIACCESSKEY"
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 31416
            name: manager
            protocol: TCP
  selector:
    matchLabels:
      app: boincseti
---
apiVersion: v1
kind: Service
metadata:
  name: boincseti
  # namespace: boinc
  # annotations:
  #   metallb.universe.tf/address-pool: #Replace this comment with your MetalLB Pool Name
spec:
  selector:
    app: boincseti
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
    - port: 31416
      name: manager
      protocol: TCP
  type: LoadBalancer