apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "boinc-pv"
spec:
  capacity:
    storage: "3Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    path: "/opt/boinc"
    server: "172.16.0.21"
  persistentVolumeReclaimPolicy: "Recycle"
